default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: sync_dev
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV["PG_HOST"] || "localhost" %>
  port: <%= ENV["PG_PORT"] || 5432 %>


test:
  <<: *default
  database: sync_test
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV["PG_HOST"] || "localhost" %>
  port: <%= ENV["PG_PORT"] || 5432 %>


production:
  primary: &primary_production
    <<: *default
    database: realbid_7pfa
    username: realbid_7pfa_user
    host: dpg-d3qda9vdiees73aa3jc0-a
    password: <%= ENV["SYNC_CHAT_DATABASE_PASSWORD"] %>
    port: 5432
    sslmode: require

  cache:
    <<: *primary_production
    database: realbid_7pfa
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: realbid_7pfa
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: realbid_7pfa
    migrations_paths: db/cable_migrate
